"use client";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { useState } from "react";

const faqData = [
  {
    question: "What does ghostwriting mean?",
    answer:
      "Ghostwriting involves an expert creating content on behalf of someone else, who is credited as the author. The ghostwriter crafts books, articles, speeches, or other forms of written material, ensuring it reflects the client's voice, ideas, and style. This service allows individuals to share their stories, knowledge, or expertise without having to write the material themselves, maintaining complete ownership of the final product.",
  },
  {
    question: "Why hire a ghostwriting agency? Do they have affordable ghostwriting packages?",
    answer:
      "Hiring a ghostwriting agency offers access to skilled writers who specialize in various genres and styles. Agencies have the resources to match your project with a writer whose expertise aligns with your vision, ensuring high-quality content that resonates with your target audience. Moreover, agencies like ours offer diverse packages designed to suit different needs and budgets, making professional ghostwriting services accessible without burning a hole in your pockets.",
  },
  {
    question: "Are your ghostwriting services 100% confidential?",
    answer:
      "Absolutely. We're like the ghostwriters that no one sees. Your project stays private – always! We take strict measures to protect your identity and the details of your project. Our writers sign Non-Disclosure Agreements (NDAs) to ensure your privacy, and all communications and materials are securely handled. Even our writers remain unaware of your personal information, guaranteeing your project is completed with the highest level of discretion.",
  },
  {
    question: "Is there an option to choose my ghostwriter?",
    answer:
      "While we don't allow you to choose your ghostwriter directly, we carefully match you with a writer who best suits your project's needs. After a thorough evaluation of your goals and preferences during the initial consultation, we assign you a professional whose expertise aligns with your genre or subject matter. This way, you can be confident that you're collaborating with a writer who understands your vision and can bring it to life effectively.",
  },
  {
    question: "What are your company's ghostwriting services rates? Is it expensive?",
    answer:
      "Our service rates are competitive and vary based on the project's scope, length, complexity, and urgency. We offer customized pricing to accommodate different budgets, ensuring you receive exceptional value for your investment. So, be at ease! While premium ghostwriting does come at a cost, we provide flexible payment plans and packages to make our affordable ghostwriting services as accessible as possible.",
  },
  {
    question: "Do your ghostwriters provide academic writing services like essays, theses, and research papers?",
    answer:
      "Yes, we have a team of qualified writers specializing in academic writing, including essays, theses, and research papers. Our academic ghostwriters are experienced in various fields and follow rigorous research and writing standards to deliver well-structured and thoroughly researched academic content. Whether you need help with a dissertation or a complicated paper, we have experts ready to assist.",
  },
  {
    question: "Do ghostwriters get royalties?",
    answer:
      "Typically, ghostwriters do not receive royalties. Instead, they are compensated with a one-time fee for their services, which is agreed upon before the project begins. This means the client retains all rights and any future profits generated by the work. However, specific arrangements can be made if both parties agree, but this is less common in standard ghostwriting contracts.",
  },
  {
    question: "How long does it take ProGhostwritingServices.com to complete my project?",
    answer:
      "The time required to complete a ghostwriting project depends on several factors, including the length, complexity, and scope of the work. For example, a standard book project might take anywhere from a few months to a year, while shorter pieces like articles, blogs, etc. can be completed within a few weeks or so. Rest assured, our reliable ghostwriting services prioritize delivering quality work within agreed timelines and keep you updated throughout the process to ensure your project meets all expectations.",
  },
];

export default function Accordions() {
  const [openItem, setOpenItem] = useState(null);

  const handleToggle = (index) => {
    setOpenItem((prev) => (prev === index ? null : index));
  };

  // Split the FAQ data into two columns for larger screens
  const leftColumn = faqData.slice(0, Math.ceil(faqData.length / 2));
  const rightColumn = faqData.slice(Math.ceil(faqData.length / 2));

  return (
    <div className="m-4 sm:m-6 lg:m-8 h-min">
      <h2 className=" bg-clip-text bg-gradient-to-r to-blue from-darkblue font-bold text-3xl md:text-4xl mb-6 text-center  ">
        Frequently Asked Questions
      </h2>
{/* Left Column */}
      <div className="flex flex-col lg:flex-row gap-4 h-auto">
        <div className="flex flex-col gap-4 lg:w-1/2">
          {leftColumn.map((faq, index) => (
            <div className="border rounded-lg p-3 w-full h-min transition-all" key={index}>
              <Accordion>
                <AccordionItem value={`item-${index}`}  >
                  <AccordionTrigger onClick={() => handleToggle(index)} className="transition-all">
                    <p className="text-left md:text-[16px] text-[14px] text-darkblue  font-medium">{faq.question}</p>
                  </AccordionTrigger>
                  {openItem === index && (
                    <AccordionContent>
                      <p className="mt-1 text-gray-700 md:h-20 lg:h-40 xl:h-24 sm:h-40 md:text-[16px] text-[14px]  text-wrap">{faq.answer}</p>
                    </AccordionContent>
                  )}
                </AccordionItem>
              </Accordion>
            </div>
          ))}
        </div>

        {/* Right Column */}

        <div className="flex flex-col gap-4 lg:w-1/2 h-auto">
          {rightColumn.map((faq, index) => (
            <div className="border rounded-lg p-3 w-full h-min transition-all " key={index + leftColumn.length}>
              <Accordion>
                <AccordionItem value={`item-${index + leftColumn.length}`}>
                  <AccordionTrigger onClick={() => handleToggle(index + leftColumn.length)} >
                    <p className="text-left md:text-[16px] text-[14px] text-darkblue">{faq.question}</p>
                  </AccordionTrigger>
                  {openItem === index + leftColumn.length && (
                    <AccordionContent>
                      <p className="mt-1 text-gray-700 md:h-20 lg:h-40 xl:h-24 sm:h-40 text-[14px] md:text-[16px] text-wrap ">{faq.answer}</p>
                    </AccordionContent>
                  )}
                </AccordionItem>
              </Accordion>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
